### ISSUE TITLE
Copr repodata folder missing (at least on Fedora 39)

### ISSUE THREAD

**Issue by waschinski** [filiparag/hetzner_ddns#10]
Hi, when trying to update I get the following error:

```
Copr repo for hetzner_ddns owned by filiparag                                                                                     321  B/s | 341  B     00:01    
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:filiparag:hetzner_ddns':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/filiparag/hetzner_ddns/fedora-39-x86_64/repodata/repomd.xml (IP: 13.225.78.78)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:filiparag:hetzner_ddns': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

There is indeed no `repodata` folder at that address: https://download.copr.fedorainfracloud.org/results/filiparag/hetzner_ddns/fedora-39-x86_64/

Can you have a look please?

**Comment by filiparag** [comment]
Thanks for reporting the issue.

It looks like a Copr issue, as [build logs](https://download.copr.fedorainfracloud.org/results/filiparag/hetzner_ddns/fedora-39-x86_64/06988104-hetzner_ddns/builder-live.log.gz) indicate an error inside their Python code. I have marked Fedora 39 and openSUSE Tumbleweed versions for removal, as they are the only ones affected.

Until the issue is resolved, please use `fedora-rawhide-x86_64` or `epel-9-x86_64` versions from [Copr](https://copr.fedorainfracloud.org/coprs/filiparag/hetzner_ddns/), or install rpm published on [GitHub](https://github.com/filiparag/hetzner_ddns/releases/tag/0.2.4).

**Comment by waschinski** [comment]
Ironically it suddenly worked earlier today and simply got updated via `dnf` though.
